### ISSUE TITLE
Another mc bug?

### ISSUE THREAD

**Issue by lurk101** [HPCguy/Squint#53]
This should either get it right, or spit out an error!
```
int a = 1 << 0, b = 1 << 1, c = 1 << 2;

int main() {
    printf("%d %d %d\n", a, b, c);
    return 0;
}
```
I get.
```
0 1 2
```
 Should be 1 2 4

Also, unrelated, standard C does not require main to have a return value even though it's declared as int.

**Comment by HPCguy** [comment]
Closed by #54 .

PS  Bug headlines like this are kind of a dick move, no?  If you don't like the compiler, stop using it. Your headline doesn't exactly motivate me to want to improve the compiler further.  A more accurate headline would have been, "Global scalar initializers are broiken".  If you insist on the dick comments, how about, "Have you stopped beating your wife?".  It's always a great move to keep the people trying to review the issues guessing what their content is.
